spring:
  profiles:
    active: local
appinfo:
  title: 奥特曼大帝国
  des: This is a Demo API project
  url: https://www.mmtech.top
  version: 1.0
  conName: Ivan
  conUrl: https://www.mmtech.top
  conEmail: ivandjp@163.com
server:
  port: 8080
